//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_TBBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int EmployeeID { get; set; }
        public int EmployeeType_EmployeeTypeID { get; set; }
        public int Department_DepartmentID { get; set; }
        public int User_UserID { get; set; }
    
        public virtual department department { get; set; }
        public virtual employeetype employeetype { get; set; }
        public virtual user user { get; set; }
    }
}
