//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_TBBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident
    {
        public int IncidentID { get; set; }
        public string IncidentTitle { get; set; }
        public string IncidentDescription { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Status { get; set; }
        public int Urgency_UrgencyID { get; set; }
        public int User_UserID { get; set; }
        public int Employee_EmployeeID { get; set; }
        public int Employee_Department_DepartmentID { get; set; }
    
        //public virtual urgency urgency { get; set; }
        public virtual user user { get; set; }
    }
}
